### ISSUE TITLE
轉換到/從日本語新字體、舊字體失敗

### ISSUE THREAD

**Issue by BSBMteam** [CXuesong/OpenCCSharp.WebApp#2]
使用了下面的測試文字：
`韋伯的任務是尋找最早、最遙遠的恆星和星系，這些恆星和星系出現在137億年前，從宇宙大爆炸（發生在138億年前）後的塵霧中誕生。`

不管是Hans、Hant、HK、TW（Shinjitai、Kyujitai之外的所有選項），轉換到Kyujitai、Shinjitai失敗，有下面的信息：

```
转换失败

Error: 指定的转换对不受支持：Hant -> Kyujitai。 at i (https://cxuesong.github.io/OpenCCSharp.WebApp/15.index.js:1:515) at async https://cxuesong.github.io/OpenCCSharp.WebApp/index.js:1:149502
```

從Kyujitai、Shinjitai轉換到Hans、Hant、HK、TW（Shinjitai、Kyujitai之外的所有選項）時，顯示下面的：

```
转换失败

Error: 指定的转换对不受支持：Kyujitai -> Hans。 at i (https://cxuesong.github.io/OpenCCSharp.WebApp/15.index.js:1:515) at async https://cxuesong.github.io/OpenCCSharp.WebApp/index.js:1:149502
```

**Comment by CXuesong** [comment]
个人理解，由于日语旧字体和新字体与中文的繁简之间并没有非常明确的对应关系，所以我在OpenCC#的转换系统里面有意区分“日语旧字体”和“OpenCC繁体”（虽然使用的转换规则是OpenCC原版的繁体和新字体之间的对应关系）。即对于日语而言，仅存在旧字体<-->新字体之间的转换关系。旧字体、新字体和其他中文字形之间的转换都是“没有意义”的。不知题主对此有何看法？还请不胜赐教。

**Comment by BSBMteam** [comment]
转换失败

Error: 指定的转换对不受支持：Hant -> Kyujitai。 at i (https://cxuesong.github.io/OpenCCSharp.WebApp/15.index.js:1:515) at async https://cxuesong.github.io/OpenCCSharp.WebApp/index.js:1:149502

**Comment by BSBMteam** [comment]
這個問題還沒修改
